/* lib_streamlink_gtk_plugin_player_vlc.vapi generated by vala-language-server, do not modify. */

namespace StreamlinkGtk {
	namespace PlayerProviders {
		[CCode (cheader_filename = "vlc.h")]
		public class Vlc : GLib.Object, StreamlinkGtk.Interfaces.IExecOptions {
			public Vlc ();
			public Gtk.Widget get_preferences ();
			public string exec_path { get; construct; }
			public string exec_path2 { get; construct; }
		}
	}
}
